apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: default
spec:
  selector:
    app: web
  type: NodePort    
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000