---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-site
  namespace: default
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: test-container
          image: test-api
          imagePullPolicy: Never
          env:
            - name: TZ
              value: America/Tijuana
          ports:
            - containerPort: 3000