apiVersion: v1
kind: Service
metadata:
  name: consume-service
  namespace: default
spec:
  selector:
    app: test
  type: NodePort    
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3001